export type PlanningKind = "sav" | "intervention";
export type PlanningPriority = "Basse" | "Normale" | "Haute" | "Urgente";

export interface PlanningItem {
  id: string;
  kind: PlanningKind;
  reference: string;
  title: string;
  company: string;
  contact: string;
  phone: string;
  address: string;
  coordinates: [number, number];
  date: string;
  time?: string;
  duration?: string;
  team: string;
  priority: PlanningPriority;
  status: string;
  equipment: string;
  description: string;
  source: "dashboard" | "dolibarr";
}

export interface ProximitySuggestion {
  id: string;
  interventionId: string;
  savId: string;
  travelMinutes: number;
  distanceKm: number;
  label: string;
}

export const interventions: PlanningItem[] = [
  {
    id: "int-2048",
    kind: "intervention",
    reference: "DOL-2048",
    title: "Mise en service PAC",
    company: "Clinique des Brotteaux",
    contact: "Sophie Bernard",
    phone: "04 72 00 18 42",
    address: "17 rue Louis Guérin, 69100 Villeurbanne",
    coordinates: [45.7748, 4.8589],
    date: "2026-08-03",
    time: "09:00",
    duration: "2 h",
    team: "Dima",
    priority: "Normale",
    status: "Confirmée",
    equipment: "Daikin Altherma 3 H HT",
    description: "Mise en service et contrôle de conformité de l’installation.",
    source: "dolibarr",
  },
  {
    id: "int-2049",
    kind: "intervention",
    reference: "DOL-2049",
    title: "Entretien annuel",
    company: "Résidence Lumière",
    contact: "Marc Aubert",
    phone: "04 78 31 40 90",
    address: "6 avenue Jean Jaurès, 69007 Lyon",
    coordinates: [45.7466, 4.8417],
    date: "2026-08-04",
    time: "08:30",
    duration: "1 h 30",
    team: "Radu",
    priority: "Normale",
    status: "Confirmée",
    equipment: "Atlantic Alféa Excellia",
    description: "Entretien annuel réglementaire et relevé des paramètres.",
    source: "dolibarr",
  },
  {
    id: "int-2050",
    kind: "intervention",
    reference: "DOL-2050",
    title: "Remplacement circulateur",
    company: "Ateliers Perrache",
    contact: "Luc Martin",
    phone: "04 72 41 66 10",
    address: "29 quai Perrache, 69002 Lyon",
    coordinates: [45.7392, 4.8226],
    date: "2026-08-05",
    time: "13:30",
    duration: "2 h",
    team: "Mihai",
    priority: "Haute",
    status: "Confirmée",
    equipment: "Mitsubishi Ecodan",
    description: "Remplacement du circulateur primaire déjà diagnostiqué.",
    source: "dolibarr",
  },
  {
    id: "int-2051",
    kind: "intervention",
    reference: "DOL-2051",
    title: "Réglage loi d’eau",
    company: "Maison Reynaud",
    contact: "Élise Reynaud",
    phone: "04 78 90 11 04",
    address: "4 rue Pierre Brunier, 69300 Caluire-et-Cuire",
    coordinates: [45.8003, 4.8412],
    date: "2026-08-06",
    time: "10:00",
    duration: "1 h",
    team: "Dima",
    priority: "Basse",
    status: "À confirmer",
    equipment: "Hitachi Yutaki S",
    description: "Ajustement de la courbe de chauffe avec le client.",
    source: "dolibarr",
  },
  {
    id: "int-2052",
    kind: "intervention",
    reference: "DOL-2052",
    title: "Réception chantier",
    company: "SCI Montchat",
    contact: "Paul Garnier",
    phone: "04 26 18 09 32",
    address: "82 cours Richard-Vitton, 69003 Lyon",
    coordinates: [45.7558, 4.885],
    date: "2026-08-07",
    time: "14:00",
    duration: "1 h 30",
    team: "Radu",
    priority: "Normale",
    status: "Confirmée",
    equipment: "Panasonic Aquarea",
    description: "Réception technique et remise du dossier au client.",
    source: "dolibarr",
  },
];

export const savItems: PlanningItem[] = [
  {
    id: "sav-2608",
    kind: "sav",
    reference: "SAV-2608",
    title: "Défaut pression circuit",
    company: "Maison Dupont",
    contact: "Claire Dupont",
    phone: "06 12 34 56 78",
    address: "38 rue Garibaldi, 69006 Lyon",
    coordinates: [45.7708, 4.8523],
    date: "2026-08-03",
    team: "Non affectée",
    priority: "Urgente",
    status: "Nouveau",
    equipment: "Daikin Altherma 3",
    description: "Arrêt intermittent avec code pression signalé par le client.",
    source: "dashboard",
  },
  {
    id: "sav-2609",
    kind: "sav",
    reference: "SAV-2609",
    title: "Bruit unité extérieure",
    company: "Boulangerie Saint-Paul",
    contact: "Nicolas Faure",
    phone: "06 30 82 10 44",
    address: "12 rue Juiverie, 69005 Lyon",
    coordinates: [45.7646, 4.8275],
    date: "2026-08-03",
    team: "Non affectée",
    priority: "Haute",
    status: "À qualifier",
    equipment: "Atlantic Alféa Extensa",
    description: "Vibration importante au démarrage de l’unité extérieure.",
    source: "dashboard",
  },
  {
    id: "sav-2610",
    kind: "sav",
    reference: "SAV-2610",
    title: "Absence d’eau chaude",
    company: "Cabinet Morel",
    contact: "Anne Morel",
    phone: "06 73 28 91 20",
    address: "21 rue de la République, 69600 Oullins",
    coordinates: [45.7151, 4.8062],
    date: "2026-08-04",
    team: "Non affectée",
    priority: "Urgente",
    status: "Nouveau",
    equipment: "Mitsubishi Ecodan Duo",
    description: "Le ballon ne monte plus en température depuis la veille.",
    source: "dashboard",
  },
  {
    id: "sav-2611",
    kind: "sav",
    reference: "SAV-2611",
    title: "Thermostat non connecté",
    company: "Résidence Confluence",
    contact: "Michel Rousset",
    phone: "06 15 40 77 02",
    address: "50 quai Rambaud, 69002 Lyon",
    coordinates: [45.7398, 4.8154],
    date: "2026-08-05",
    team: "Non affectée",
    priority: "Normale",
    status: "À planifier",
    equipment: "Mitsubishi Ecodan",
    description: "Perte de communication entre le thermostat et le module.",
    source: "dashboard",
  },
  {
    id: "sav-2612",
    kind: "sav",
    reference: "SAV-2612",
    title: "Consommation anormale",
    company: "Villa des Canuts",
    contact: "Julie Blanc",
    phone: "06 44 18 05 99",
    address: "9 rue de Cuire, 69004 Lyon",
    coordinates: [45.7809, 4.8305],
    date: "2026-08-05",
    team: "Non affectée",
    priority: "Haute",
    status: "À qualifier",
    equipment: "Hitachi Yutaki S",
    description: "Hausse de consommation constatée sur les deux dernières semaines.",
    source: "dashboard",
  },
  {
    id: "sav-2613",
    kind: "sav",
    reference: "SAV-2613",
    title: "Radiateurs tièdes",
    company: "Maison Garnier",
    contact: "Alain Garnier",
    phone: "06 51 90 23 18",
    address: "41 rue Ferdinand Buisson, 69003 Lyon",
    coordinates: [45.7548, 4.8766],
    date: "2026-08-07",
    team: "Non affectée",
    priority: "Normale",
    status: "À planifier",
    equipment: "Panasonic Aquarea",
    description: "Température de départ correcte mais émetteurs insuffisamment chauds.",
    source: "dashboard",
  },
  {
    id: "sav-2614",
    kind: "sav",
    reference: "SAV-2614",
    title: "Erreur sonde extérieure",
    company: "École Sainte-Marie",
    contact: "François Leclerc",
    phone: "06 22 11 47 65",
    address: "7 rue du 8 Mai 1945, 69100 Villeurbanne",
    coordinates: [45.7685, 4.8792],
    date: "2026-08-06",
    team: "Non affectée",
    priority: "Haute",
    status: "En attente client",
    equipment: "Daikin Altherma",
    description: "Code défaut sonde extérieure, accès technique à confirmer.",
    source: "dashboard",
  },
  {
    id: "sav-2615",
    kind: "sav",
    reference: "SAV-2615",
    title: "Fuite sous module",
    company: "Loft Vaise",
    contact: "Camille Robert",
    phone: "06 84 32 10 73",
    address: "16 quai Paul Sédallian, 69009 Lyon",
    coordinates: [45.7914, 4.8112],
    date: "2026-08-07",
    team: "Non affectée",
    priority: "Urgente",
    status: "Nouveau",
    equipment: "Atlantic Alféa Excellia",
    description: "Présence d’eau sous le module hydraulique signalée ce matin.",
    source: "dashboard",
  },
];

export const proximitySuggestions: ProximitySuggestion[] = [
  {
    id: "suggestion-1",
    interventionId: "int-2048",
    savId: "sav-2608",
    travelMinutes: 12,
    distanceKm: 3.2,
    label: "Dima · Dupont",
  },
  {
    id: "suggestion-2",
    interventionId: "int-2050",
    savId: "sav-2611",
    travelMinutes: 8,
    distanceKm: 1.4,
    label: "Mihai · Résidence Confluence",
  },
  {
    id: "suggestion-3",
    interventionId: "int-2052",
    savId: "sav-2613",
    travelMinutes: 15,
    distanceKm: 2.7,
    label: "Radu · Maison Garnier",
  },
];

export const allPlanningItems = [...interventions, ...savItems];

